[package]
name = "ui"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]

[dependencies]
boggle = { path = ".." }
yew = { git = "https://github.com/DenisKolodin/yew" }
rand = { version = "0.5.4", features = ["stdweb"] }
dict = { path = "../dict" }
